Repository playframework/play-ebean, pull requests merged in 2023-05, with the labels that each got.

#367 Sync `headerEmptyLine` setting with core repo
  play-ebean/src/main/java/play/db/ebean/DefaultEbeanConfig.java
  play-ebean/src/main/java/play/db/ebean/EBeanComponents.java
  play-ebean/src/main/java/play/db/ebean/EbeanConfig.java
  play-ebean/src/main/java/play/db/ebean/EbeanDynamicEvolutions.java
  play-ebean/src/main/java/play/db/ebean/EbeanModule.java
  play-ebean/src/main/java/play/db/ebean/EbeanParsedConfig.java
  play-ebean/src/main/java/play/db/ebean/ModelsConfigLoader.java
  play-ebean/src/main/java/play/db/ebean/Transactional.java
  play-ebean/src/main/java/play/db/ebean/TransactionalAction.java
  play-ebean/src/main/java/play/db/ebean/package-info.java
  play-ebean/src/test/java/play/db/ebean/EBeanComponentsTest.java
  play-ebean/src/test/java/play/db/ebean/EbeanParsedConfigTest.java
  project/Common.scala
  sbt-play-ebean/src/main/scala/play/ebean/sbt/PlayEbean.scala
Labels: status:merge-when-green

#370 🔄 synced file(s) with playframework/.github
  build.sbt
  common.sbt
  docs/build.sbt
  docs/common.sbt
Labels: sync

#373 sbt 1.8.3 (was 1.8.2)
  docs/project/build.properties
  project/build.properties
Labels: type:updates

#371 sbt-ci-release 1.5.12 (was 1.5.11)
  project/plugins.sbt
Labels: type:updates
